/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bountyCollectModuleSol from "./BountyCollectModule.sol";
export type { bountyCollectModuleSol };
export type { AcceptedAnswerNFT } from "./AcceptedAnswerNFT";
export type { MockERC20 } from "./MockERC20";
