/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type ProcessActionParamsStruct = {
    publicationActedProfileId: BigNumberish;
    publicationActedId: BigNumberish;
    actorProfileId: BigNumberish;
    actorProfileOwner: AddressLike;
    transactionExecutor: AddressLike;
    referrerProfileIds: BigNumberish[];
    referrerPubIds: BigNumberish[];
    referrerPubTypes: BigNumberish[];
    actionModuleData: BytesLike;
  };

  export type ProcessActionParamsStructOutput = [
    publicationActedProfileId: bigint,
    publicationActedId: bigint,
    actorProfileId: bigint,
    actorProfileOwner: string,
    transactionExecutor: string,
    referrerProfileIds: bigint[],
    referrerPubIds: bigint[],
    referrerPubTypes: bigint[],
    actionModuleData: string
  ] & {
    publicationActedProfileId: bigint;
    publicationActedId: bigint;
    actorProfileId: bigint;
    actorProfileOwner: string;
    transactionExecutor: string;
    referrerProfileIds: bigint[];
    referrerPubIds: bigint[];
    referrerPubTypes: bigint[];
    actionModuleData: string;
  };
}

export interface BountyCollectModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptedAnswerNFT"
      | "initializePublicationAction"
      | "owner"
      | "processPublicationAction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BountyInitialized" | "BountyPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptedAnswerNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializePublicationAction",
    values: [BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPublicationAction",
    values: [Types.ProcessActionParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptedAnswerNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializePublicationAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPublicationAction",
    data: BytesLike
  ): Result;
}

export namespace BountyInitializedEvent {
  export type InputTuple = [
    profileId: BigNumberish,
    pubId: BigNumberish,
    currency: AddressLike,
    amount: BigNumberish,
    asker: AddressLike
  ];
  export type OutputTuple = [
    profileId: bigint,
    pubId: bigint,
    currency: string,
    amount: bigint,
    asker: string
  ];
  export interface OutputObject {
    profileId: bigint;
    pubId: bigint;
    currency: string;
    amount: bigint;
    asker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyPaidEvent {
  export type InputTuple = [
    profileId: BigNumberish,
    pubId: BigNumberish,
    expertAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    profileId: bigint,
    pubId: bigint,
    expertAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    profileId: bigint;
    pubId: bigint;
    expertAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BountyCollectModule extends BaseContract {
  connect(runner?: ContractRunner | null): BountyCollectModule;
  waitForDeployment(): Promise<this>;

  interface: BountyCollectModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptedAnswerNFT: TypedContractMethod<[], [string], "view">;

  initializePublicationAction: TypedContractMethod<
    [
      profileId: BigNumberish,
      pubId: BigNumberish,
      transactionExecutor: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processPublicationAction: TypedContractMethod<
    [processActionParams: Types.ProcessActionParamsStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptedAnswerNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initializePublicationAction"
  ): TypedContractMethod<
    [
      profileId: BigNumberish,
      pubId: BigNumberish,
      transactionExecutor: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPublicationAction"
  ): TypedContractMethod<
    [processActionParams: Types.ProcessActionParamsStruct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "BountyInitialized"
  ): TypedContractEvent<
    BountyInitializedEvent.InputTuple,
    BountyInitializedEvent.OutputTuple,
    BountyInitializedEvent.OutputObject
  >;
  getEvent(
    key: "BountyPaid"
  ): TypedContractEvent<
    BountyPaidEvent.InputTuple,
    BountyPaidEvent.OutputTuple,
    BountyPaidEvent.OutputObject
  >;

  filters: {
    "BountyInitialized(uint256,uint256,address,uint256,address)": TypedContractEvent<
      BountyInitializedEvent.InputTuple,
      BountyInitializedEvent.OutputTuple,
      BountyInitializedEvent.OutputObject
    >;
    BountyInitialized: TypedContractEvent<
      BountyInitializedEvent.InputTuple,
      BountyInitializedEvent.OutputTuple,
      BountyInitializedEvent.OutputObject
    >;

    "BountyPaid(uint256,uint256,address,uint256)": TypedContractEvent<
      BountyPaidEvent.InputTuple,
      BountyPaidEvent.OutputTuple,
      BountyPaidEvent.OutputObject
    >;
    BountyPaid: TypedContractEvent<
      BountyPaidEvent.InputTuple,
      BountyPaidEvent.OutputTuple,
      BountyPaidEvent.OutputObject
    >;
  };
}
