/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BountyCollectModule } from "./BountyCollectModule";
export type { IAcceptedAnswerNFT } from "./IAcceptedAnswerNFT";
