/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  BountyCollectModule,
  BountyCollectModuleInterface,
} from "../BountyCollectModule";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "actionId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "actionId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "processData",
        type: "bytes",
      },
    ],
    name: "processAction",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610367806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806366e7990d1461003b578063c099d85214610057575b600080fd5b6100556004803603810190610050919061014d565b610087565b005b610071600480360381019061006c919061020b565b61008c565b60405161007e919061030f565b60405180910390f35b505050565b6060604051806020016040528060008152509050949350505050565b600080fd5b600080fd5b6000819050919050565b6100c5816100b2565b81146100d057600080fd5b50565b6000813590506100e2816100bc565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f84011261010d5761010c6100e8565b5b8235905067ffffffffffffffff81111561012a576101296100ed565b5b602083019150836001820283011115610146576101456100f2565b5b9250929050565b600080600060408486031215610166576101656100a8565b5b6000610174868287016100d3565b935050602084013567ffffffffffffffff811115610195576101946100ad565b5b6101a1868287016100f7565b92509250509250925092565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101d8826101ad565b9050919050565b6101e8816101cd565b81146101f357600080fd5b50565b600081359050610205816101df565b92915050565b60008060008060608587031215610225576102246100a8565b5b6000610233878288016101f6565b9450506020610244878288016100d3565b935050604085013567ffffffffffffffff811115610265576102646100ad565b5b610271878288016100f7565b925092505092959194509250565b600081519050919050565b600082825260208201905092915050565b60005b838110156102b957808201518184015260208101905061029e565b60008484015250505050565b6000601f19601f8301169050919050565b60006102e18261027f565b6102eb818561028a565b93506102fb81856020860161029b565b610304816102c5565b840191505092915050565b6000602082019050818103600083015261032981846102d6565b90509291505056fea2646970667358221220799bb3c14aa2d67aabbe45a572c7860d6e38e14c971b74f0a7aa8c2b6207c31d64736f6c63430008170033";

type BountyCollectModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BountyCollectModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BountyCollectModule__factory extends ContractFactory {
  constructor(...args: BountyCollectModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BountyCollectModule & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BountyCollectModule__factory {
    return super.connect(runner) as BountyCollectModule__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BountyCollectModuleInterface {
    return new Interface(_abi) as BountyCollectModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BountyCollectModule {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BountyCollectModule;
  }
}
