/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAcceptedAnswerNFT,
  IAcceptedAnswerNFTInterface,
} from "../../../contracts/BountyCollectModule.sol/IAcceptedAnswerNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAcceptedAnswerNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IAcceptedAnswerNFTInterface {
    return new Interface(_abi) as IAcceptedAnswerNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAcceptedAnswerNFT {
    return new Contract(address, _abi, runner) as unknown as IAcceptedAnswerNFT;
  }
}
