/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPublicationActionModule,
  IPublicationActionModuleInterface,
} from "../../../../lens-modules/contracts/interfaces/IPublicationActionModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pubId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "transactionExecutor",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initializePublicationAction",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "publicationActedProfileId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "publicationActedId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "actorProfileId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "actorProfileOwner",
            type: "address",
          },
          {
            internalType: "address",
            name: "transactionExecutor",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "referrerProfileIds",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "referrerPubIds",
            type: "uint256[]",
          },
          {
            internalType: "enum Types.PublicationType[]",
            name: "referrerPubTypes",
            type: "uint8[]",
          },
          {
            internalType: "bytes",
            name: "actionModuleData",
            type: "bytes",
          },
        ],
        internalType: "struct Types.ProcessActionParams",
        name: "processActionParams",
        type: "tuple",
      },
    ],
    name: "processPublicationAction",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPublicationActionModule__factory {
  static readonly abi = _abi;
  static createInterface(): IPublicationActionModuleInterface {
    return new Interface(_abi) as IPublicationActionModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPublicationActionModule {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPublicationActionModule;
  }
}
