/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  HubRestricted,
  HubRestrictedInterface,
} from "../../../../lens-modules/contracts/base/HubRestricted";

const _abi = [
  {
    inputs: [],
    name: "HUB",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class HubRestricted__factory {
  static readonly abi = _abi;
  static createInterface(): HubRestrictedInterface {
    return new Interface(_abi) as HubRestrictedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HubRestricted {
    return new Contract(address, _abi, runner) as unknown as HubRestricted;
  }
}
